package sim

import "errors"

var (
	ErrInsufficientFuel  = errors.New("insufficient fuel")
	ErrInsufficientFunds = errors.New("insufficient credits")
	ErrHullBreached      = errors.New("hull breached — repair required")
	ErrNotDocked         = errors.New("must be docked at port")
	ErrInBelt            = errors.New("must be docked to use port services")
	ErrActiveRun         = errors.New("mining run in progress")
	ErrNoActiveRun       = errors.New("no active mining run")
	ErrInvalidWorld      = errors.New("invalid world")
	ErrInvalidAsteroid   = errors.New("invalid asteroid")
	ErrAlreadyFull       = errors.New("already at maximum")
	ErrMaxUpgrade        = errors.New("upgrade at max level")
	ErrNotEligible       = errors.New("not eligible")
	ErrNotScanned        = errors.New("asteroid not scanned yet")
	ErrAlreadyScanned    = errors.New("asteroid already scanned")
	ErrScanInProgress    = errors.New("scan already in progress")
	ErrInvalidRunPhase   = errors.New("action not valid in current run phase")
	ErrOutOfRange        = errors.New("asteroid is beyond scanner range")
	ErrRouteLocked       = errors.New("route is locked")
	ErrInvalidSystem     = errors.New("invalid system")
	ErrAlreadyUnlocked   = errors.New("route already unlocked")
	ErrCargoEmpty        = errors.New("cargo hold is empty")
	ErrCargoFull         = errors.New("cargo hold is full — sell cargo before departing")
	ErrCargoDoesNotFit   = errors.New("cargo does not fit in the selected ship or loadout")

	// Fleet/shipyard errors (gameplay/05-fleet-ships-and-shipyard-economy.md).
	ErrShipRemote       = errors.New("ship is at another system — use the hauler ferry")
	ErrInvalidShip      = errors.New("unknown ship model")
	ErrAlreadyOwned     = errors.New("ship already owned")
	ErrNotOwned         = errors.New("ship not owned")
	ErrItemLocked       = errors.New("item is locked")
	ErrInvalidSlotItem  = errors.New("item does not fit this slot")
	ErrInvalidSlotIndex = errors.New("invalid slot index")
	ErrPowerExceeded    = errors.New("insufficient power capacity")
	ErrSlotEmpty        = errors.New("slot is empty")
	ErrSlotOccupied     = errors.New("slot already has a module — store or sell it first")
	ErrInvalidInventory = errors.New("invalid inventory item")
	ErrDuplicateItem    = errors.New("that module is already installed on this ship")

	// Combat errors (gameplay/07-pirate-combat-and-bounties.md).
	ErrNoWeaponInstalled  = errors.New("no weapon installed")
	ErrWeaponsLocked      = errors.New("weapons overheated — locked")
	ErrNoMissileLauncher  = errors.New("no missile launcher installed")
	ErrNoMissiles         = errors.New("missiles depleted — dock to reload")
	ErrMissileCoolingDown = errors.New("missile launcher cooling down")
)
